### ISSUE TITLE
[Regression] hlx build is broken

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1571]
Version: @adobe/helix-cli@13.0.1

Run `hlx build` in adobe/helix-pages:

```
$ hlx build
Cannot find module 'antlr4/index'
```

Visible on the CI: https://app.circleci.com/pipelines/github/adobe/helix-pages/2326/workflows/698f017f-e5da-4674-9111-09141884189b/jobs/9499

**Comment by kptdobe** [comment]
Same with latest version: @adobe/helix-cli@13.0.15

**Comment by tripodsan** [comment]
hmmm, weird. this is a htlengine dependency....

**Comment by tripodsan** [comment]
but why do the helix tests and smoke tests work?
https://github.com/adobe/helix-cli/pull/1570

**Comment by kptdobe** [comment]
It should be an uncovered use case because the build tests in the cli pass and the project-helix.io build also works...

**Comment by kptdobe** [comment]
Related: https://github.com/adobe/htlengine/issues/264

**Comment by kptdobe** [comment]
It seems `antlr4` just broke the world :)

**Comment by tripodsan** [comment]
should be fixed with https://github.com/adobe/helix-cli/pull/1572

**Comment by kptdobe** [comment]
Thanks for merging my PR.

I still do not get why the tests would not capture that vs issue appears after the fact. If this is because `htlengine` does not use strict dependencies (i.e. `~4.7.2`) and when installing the cli on my machine I got the broken `4.9.0`, I then think we should never use non strict dependencies... Here it is an obvious heavy breaking change but whatever minor change could have an impact somewhere and we take the risk to miss it...

**Comment by kptdobe** [comment]
Created https://github.com/adobe/htlengine/issues/266 to follow up.
